name: Test and Go
favicon: null
layout_spectrum: 0.5182759170420468
typography_spectrum: 0.41103101009503007
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.9413834568113089
  lightness: 0.11753599345684052
  saturation: 0.20216929027810693
  rhythmicContrast: 0.04378649918362498
purpose: []
